id: P008123
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD20562
  title: གཅོད་ཀྱི་ཚོགས་ལས་རིན་པོ་ཆེའི་ཕྲེང་བ་འདོན་བསྒྲིགས་བལྟས་ཆོག་ཏུ་བཀོད་པ།
  author: ''
  volumes:
    32f9a44a5e174de2ad81f213519db660:
      image_group_id: I2PD20734
      title: ''
      volume_number: 1
      total_pages: 608
ebook_metadata:
  title: གཅོད་ཀྱི་ཚོགས་ལས་རིན་པོ་ཆེའི་ཕྲེང་བ་འདོན་བསྒྲིགས་བལྟས་ཆོག་ཏུ་བཀོད་པ།
  author: ''
  sku: P008123
  cover: cover.jpg
  layers:
  - pagination
